Masha'erohom/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db   ##means from __init__.py import db
from flask_login import login_user, login_required, logout_user, current_user
import hashlib

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            hashed_password = hashlib.sha512(password.encode('utf-8')).hexdigest()

            if user.password==hashed_password:
                #flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')

    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
            return render_template("register.html", user=user, email=email, firstName=firstName)
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
            return render_template("register.html", user=user, email=email, firstName=firstName)
        elif len(firstName) < 2:
            flash('First name must be greater than 1 character.', category='error')
            return render_template("register.html", user=user, email=email, firstName=firstName)
        elif password1 != password2:
            flash('Passwords don\'t match.', category='error')
            return render_template("register.html", user=user, email=email, firstName=firstName)
        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')
            return render_template("register.html", user=user, email=email, firstName=firstName)
        else:
            password_hash = hashlib.sha512(password1.encode('utf-8')).hexdigest()
            new_user = User(email=email, first_name=firstName, password=password_hash)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            #flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("register.html", user=current_user)

Masha'erohom/website/views.py
from flask import Flask, Blueprint, render_template, request, make_response, send_from_directory, redirect, url_for , jsonify,copy_current_request_context
from flask_login import login_required, current_user
from .models import File
from werkzeug.utils import secure_filename
from datetime import datetime
from . import db
from flask import session
from RandomForestForBatches.RandomForest import get_sentiments
import pandas as pd
import os
import json
from .scraper import get_twitterSentiments
from RandomForestForBatches.RandomForest import initialize_random_forest
from flask import current_app
from concurrent.futures import ThreadPoolExecutor
from threading import Semaphore,Lock

global user_semaphore
global lock 
user_semaphore = Semaphore(5)
lock = Lock()

views = Blueprint('views', __name__)
ALLOWED_EXTENSIONS = {'csv'}
MODELS_DIR = "RandomForestForBatches/ModelsFiles/"

global dfs
dfs = dict()

def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@views.route('/', methods=['GET','POST'])
@login_required
def home():
    lock.acquire()
    if current_user.id in dfs.keys():
        del dfs[current_user.id]
    lock.release()
    if request.method=='POST':
        # Check if the file is uploaded
        if 'file' in request.files:
            file = request.files['file']
            if file and allowed_file(file.filename):
                Rfile = pd.read_csv(file)
                if 'text' in Rfile.columns:
                    df_json = Rfile.to_json(orient='records')
                    return render_template('Loading.html',dataframe = df_json, filename = file.filename)
                else:
                    return "The uploaded file does not contain a 'text' column."
            else:
                return "The uploaded file is not a CSV file."
        # Check if the keyword is submitted
        elif 'keyWord' in request.form:
            keyword = request.form['keyWord']
            matchType = request.form.get('type')
            return render_template('Loading.html',keyword = keyword,matchType = matchType)
        else:
            return "No file or keyword submitted."
    else:
        return render_template("home.html", user=current_user)

@login_required
@views.route('/download/<filename>',methods=['GET'])
def download(filename):
    return send_from_directory('predictedData', filename, as_attachment=True)

@login_required
@views.route('/chart/<filename>', methods=['GET'])
def chart(filename):
    file_path = os.path.join('predictedData', filename)
    df = pd.read_csv(file_path)

    joy_count = (df['prediction'] == 'joy').sum()
    anger_count = (df['prediction'] == 'anger').sum()
    sadness_count = (df['prediction'] == 'sadness').sum()
    love_count = (df['prediction'] == 'love').sum()
    sympathy_count = (df['prediction'] == 'sympathy').sum()
    surprise_count = (df['prediction'] == 'surprise').sum()
    fear_count = (df['prediction'] == 'fear').sum()
    none_count = (df['prediction'] == 'none').sum()

    categories = ['joy', 'anger', 'sadness', 'love', 'sympathy', 'surprise', 'fear', 'none']
    counts = [joy_count, anger_count, sadness_count, love_count, sympathy_count, surprise_count, fear_count, none_count]
    counts = [int(count) for count in counts]
    
    categories_json = json.dumps(categories)
    counts_json = json.dumps(counts)
    return render_template('Chart.html', categories=categories_json, counts=counts_json, user=current_user, filename=filename)

@login_required
@views.route('/chart2', methods=['GET','POST'])
def ChartsWithTwitter():
    if request.method=='POST' : 
        dataframe_in_json = request.json.get('dataframe')
        df = pd.read_json(json.loads(dataframe_in_json))
        dfs[current_user.id] = df
        return "successfully populated analysis data"
    else :
        lock.acquire()
        df = dfs.get(current_user.id)
        lock.release()
        if df is None : 
            return redirect(url_for('views.home'))
        joy_count = (df['prediction'] == 'joy').sum()
        anger_count = (df['prediction'] == 'anger').sum()
        sadness_count = (df['prediction'] == 'sadness').sum()
        love_count = (df['prediction'] == 'love').sum()
        sympathy_count = (df['prediction'] == 'sympathy').sum()
        surprise_count = (df['prediction'] == 'surprise').sum()
        fear_count = (df['prediction'] == 'fear').sum()
        none_count = (df['prediction'] == 'none').sum()
        categories = ['joy', 'anger', 'sadness', 'love', 'sympathy', 'surprise', 'fear', 'none']
        counts = [joy_count, anger_count, sadness_count, love_count, sympathy_count, surprise_count, fear_count, none_count]
        counts = [int(count) for count in counts]
        tweetsJson = df['text'].to_json(orient='records')
        tweetsclsJson = df['prediction'].to_json(orient='records')
        tweetsLinksJson = df['tweetUrl'].to_json(orient='records')
        categories_json = json.dumps(categories)
        counts_json = json.dumps(counts)
        return render_template('ChartsWithTwitter.html', categories=categories_json, counts=counts_json, user=current_user,tweet = tweetsJson,emotion = tweetsclsJson,tweetsLink = tweetsLinksJson)
    


@views.route('/History')
def History():
        user_files = File.query.filter_by(user_id=current_user.id).all()
        return render_template('history.html', user_files=user_files, user=current_user)
  
def twitter_scraping(keyword,matchType):
    try:
        user_semaphore.acquire()
        initialize_random_forest(f"{MODELS_DIR}Random_Forest.joblib",f"{MODELS_DIR}bert_classifier_model.pth",  f"{MODELS_DIR}tokenizer.pkl",f"{MODELS_DIR}BiLSTM_model.h5" ,f"{MODELS_DIR}BiGRU_model.h5",f"{MODELS_DIR}tokenizer_config.json")
        df = get_twitterSentiments(keyword=keyword,searchType=matchType)
        return df
    finally:
        user_semaphore.release()
        
    
    
    
@views.route('/start-twitter-task',methods=['GET'])
def start_twitter_task():
    keyword = request.args.get('keyword')
    matchType = request.args.get('matchtype')
    with ThreadPoolExecutor(max_workers=1) as executor:
        future =  executor.submit(twitter_scraping,keyword,matchType)
        result = future.result()
        result = result.to_json()
        return jsonify({'dataframe': result})

@views.route('/start-file-task',methods=['POST'])
def start_file_task():
    initialize_random_forest(f"{MODELS_DIR}Random_Forest.joblib",f"{MODELS_DIR}bert_classifier_model.pth",  f"{MODELS_DIR}tokenizer.pkl",f"{MODELS_DIR}BiLSTM_model.h5" ,f"{MODELS_DIR}BiGRU_model.h5",f"{MODELS_DIR}tokenizer_config.json")
    data = request.get_json()
    df = pd.read_json(json.dumps(data.get('dataframe')))
    classifications = get_sentiments(df['text'])
    df['prediction'] = classifications
    filename = data.get('file_name')
    filename = secure_filename(filename)
    new_filename = f'{filename.split(".")[0]}_predicted_{str(datetime.now()).replace(":", "-")}.csv' 
    save_location = os.path.join('predictedData', new_filename)
    df.to_csv(save_location, index=False)
    new_file = File(file_name=new_filename, user_id=current_user.id)
    db.session.add(new_file)
    db.session.commit()
    return jsonify({'filename' : new_filename })

@login_required
@views.route('/About-Us',methods = ['GET'])
def aboutUS():
    return render_template('AboutUs.html',user = current_user)

@views.route('predict_emotion',methods = ['POST'])
def predict_emotion():
    initialize_random_forest(f"{MODELS_DIR}Random_Forest.joblib",f"{MODELS_DIR}bert_classifier_model.pth",  f"{MODELS_DIR}tokenizer.pkl",f"{MODELS_DIR}BiLSTM_model.h5" ,f"{MODELS_DIR}BiGRU_model.h5",f"{MODELS_DIR}tokenizer_config.json")
    data = request.get_json()
    keyword = data['text']
    print(keyword)
    response = get_sentiments([keyword])[0]
    print(response)
    return jsonify({'emotion': response})

Masha'erohom/website/templates/Chart.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bar and Pie Chart Example</title>
    <!-- Include Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@200..1000&display=swap');
        *{
            font-family:'Cairo',sans-serif;
            font-weight:600;
        }
        table {
            direction: rtl;
            border-collapse: collapse;
            width: 70%; /* Adjusted width of the table container */
        }
        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        .container-fluid{
            padding-top: 1.35%;
            padding-left: 15%;
            padding-right: 15%;
        }
        th {
            background-color: #f2f2f2;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        /* Adjusted width of the pie chart container */
        #pieChartContainer {
            width: 20%;
            position: relative;
        }
        /* Adjusted width and height of the pie chart canvas */
        #pieChart {
            width: 300px;
            height: 300px;
        }
        /* Style for the button */
        .button {
            position: absolute;
            bottom: 10px;
            left: 50%;
            transform: translateX(-50%);
            background-color: #4CAF50;
            border: none;
            color: white;
            padding: 10px 20px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 4px 2px;
            cursor: pointer;
            border-radius: 5px;
        }
        /* Hover effect for the button */
        .button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
    <!-- Create a container for the charts and table -->
    <div style="display: flex;">
        <!-- Create a canvas element to render the bar chart -->
        <div style="width: 50%;">
            <canvas id="barChart" width="400" height="300"></canvas>
        </div>
        <!-- Create a canvas element to render the pie chart -->
        <div id="pieChartContainer" style="width: 25%;"> <!-- Adjusted width of the pie chart container -->
            <canvas id="pieChart" width="300" height="300"></canvas> <!-- Adjusted width and height of the pie chart canvas -->
            <!-- Button to redirect to home page -->
            <a href="{{ url_for('views.download', filename=filename) }}" class="button">تحميل الملف</a>
        </div>
        <!-- Create a table to display category counts -->
        <div style="width: 20%;">
            <table>
                <thead>
                    <tr>
                        <th>الشعور</th>
                        <th>العدد</th>
                        <th>العدد </th>

                    </tr>
                </thead>
                <tbody id="categoryTable">
                    <!-- Table rows will be dynamically generated -->
                </tbody>
            </table>
        </div>
    </div>

    <!-- JavaScript Section -->
    <script>
        // Get data from Flask view
        var categories = JSON.parse('{{ categories | safe }}');
        var counts = JSON.parse('{{ counts | safe }}');
        const translations ={
            'joy': 'سعادة',
            'love': 'حب',
            'none': 'لا شعور',
            'fear':'خوف',
            'surprise': 'اندهاش',
            'sympathy' : 'تعاطف',
            'anger':'غضب',
            'sadness':'حزن'
        }

        categories = categories.map(category => translations[category]);

       // Define custom colors for the charts
       var colors = [
       'rgba(255, 206, 86, 0.5)',   
       'rgba(255, 0, 0, 0.5)',    
       'rgba(54, 162, 235, 0.5)',    
       'rgba(255, 192, 203, 0.5)',    
       'rgba(153, 102, 255, 0.5)',   
       'rgba(255, 159, 64, 0.5)',   
       'rgba(0, 0, 0, 0.5)',  
       'rgba( 150, 150, 150, 0.5)'     
   ];

        // Define data for the bar chart
        var barChartData = {
            labels: categories,
            datasets: [{
                label: 'Emotion Counts',
                data: counts,
                backgroundColor: colors.slice(0, categories.length), // Use colors for available categories
                borderColor: colors.slice(0, categories.length).map(color => color.replace('0.5', '1')), // Set border color for bars
                borderWidth: 1
            }]
        };

        // Define data for the pie chart
        var pieChartData = {
            labels: categories,
            datasets: [{
                data: counts,
                backgroundColor: colors.slice(0, categories.length), // Use colors for available categories
                borderColor: 'rgba(255, 255, 255, 1)', // Set border color for pie chart
                borderWidth: 1
            }]
        };

       // Configure options for both charts
       var options = {
        scales: {
            y: {
                ticks: {
                    beginAtZero: true,
                    display: true // hide the numbers on y-axis
                }
            },
            x: {
                ticks: {
                    beginAtZero: true,
                    display: true, // hide the numbers on y-axis
                    font:{
                    size:18
                    }
                }
            }
        },

        plugins: {
        title: {
            display: true,
            text: 'توزيع المشاعر', // Set the title text here
            font:{
                size : 20
            } // Set the font size for the title
        },
        legend: {
            display: false // Hide legend if not needed
        }
    }
    };


        // Configure options for the pie chart with percentage scale
        var pieChartOptions = {
            title: {
                display: true,
                text: 'Emotion Distribution'
                
            },
            tooltips: {
                callbacks: {
                    label: function(tooltipItem, data) {
                        var dataset = data.datasets[tooltipItem.datasetIndex];
                        var total = dataset.data.reduce(function(previousValue, currentValue, currentIndex, array) {
                            return previousValue + currentValue;
                        });
                        var currentValue = dataset.data[tooltipItem.index];
                        var percentage = Math.round((currentValue / total) * 100);
                        return categories[tooltipItem.index] + ': ' + currentValue + ' (' + percentage + '%)';
                    }
                }
            },
            plugins: {
                legend: {
                    labels: {
                        font: {
                            size: 14, // Set the font size for legend labels
                            family: 'Arial', // Set the font family for legend labels
                            weight: 'bold' // Set the font weight for legend labels
                        }
                    }
                }
            }

        };

        // Get the canvas elements for both charts
        var barCtx = document.getElementById('barChart').getContext('2d');
        var pieCtx = document.getElementById('pieChart').getContext('2d');

        // Create a new bar chart instance
        var barChart = new Chart(barCtx, {
            type: 'bar',
            data: barChartData,
            options: options
        });

        // Create a new pie chart instance with percentage scale
        var pieChart = new Chart(pieCtx, {
            type: 'pie',
            data: pieChartData,
            options: pieChartOptions
        });

        // Populate the table with category counts
        var categoryTable = document.getElementById('categoryTable');
        for (var i = 0; i < categories.length; i++) {
            var row = document.createElement('tr');
            var categoryCell = document.createElement('td');
            var countCell = document.createElement('td');
            var percentageCell = document.createElement('td');
            var percentage = Math.round((counts[i] / counts.reduce((a, b) => a + b, 0)) * 100); // Calculate percentage
            categoryCell.textContent = categories[i];
            countCell.textContent = counts[i];
            percentageCell.textContent = percentage + '%';
            row.appendChild(categoryCell);
            row.appendChild(countCell);
            row.appendChild(percentageCell);
            categoryTable.appendChild(row);
        }
    </script>
</body>
</html>
{% endblock %}

Masha'erohom/website/templates/History.html
{% extends "base.html" %}
{% block title %}السجل{% endblock %}
{% block content %}
<style>
    body{
        background-position: initial;
    }

</style>
<div class="container">
    <h1 class="text-center mt-4 mb-4">Files</h1>

    <ul class="list-group">
        {% for file in user.files %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            <span>{{ file.file_name }}</span>
            <a href="{{ url_for('views.download', filename=file.filename) }}" class="btn btn-primary">Download</a>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

Masha'erohom/website/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <title>Login Page</title>
    <style>
        .alert-danger{
            background-color: #ff727299;
            box-sizing: border-box;
            border-radius: 20px;
            padding: 20px;
            text-align: center;
        }
        .close{
            background: none;
            border: none;
        }
        .dismissBtnTextspan{
            font-size: 30px;
            margin-left: 30px;
        }
        .alert-success{
            background-color: #9aff7299;
            box-sizing: border-box;
            border-radius: 20px;
            padding: 20px;
            text-align: center;
        }
        

    </style>
</head>

<body>
    {% with messages = get_flashed_messages(with_categories=true) %} {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" class = "dismissBtnTextspan">&times;</span>
        </button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true" class = "dismissBtnTextspan">&times;</span>
        </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <div class="container" id="container">
        <div class="form-container sign-up">
            <form method="post" action="{{ url_for('auth.sign_up') }}">
                <h1>Create Account</h1>
                <div class="social-icons">
                    <a href="#" class="icon"><i class="fa-brands fa-google-plus-g"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-linkedin-in"></i></a>
                </div>
                <span>or use your email for registration</span>
                <input type="email" id="email" name="email" placeholder="Email">
                <input type="text" id="firstName" name="firstName" placeholder="Name">
                <input type="password" id="password1" name="password1" placeholder="Password">
                <input type="password" id="password2" name="password2" placeholder="Confirm Password">
                <button type="submit">Sign Up</button>
            </form>
        </div>
        <div class="form-container sign-in">
            <form method="post" action="{{ url_for('auth.login') }}">
                <h1>Sign In</h1>
                <div class="social-icons">
                    <a href="#" class="icon"><i class="fa-brands fa-google-plus-g"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-facebook-f"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-github"></i></a>
                    <a href="#" class="icon"><i class="fa-brands fa-linkedin-in"></i></a>
                </div>
                <span>or use your email password</span>
                <input type="email" id="email" name="email" placeholder="Email">
                <input type="password" id="password" name="password" placeholder="Password">
                <a href="#">Forget Your Password?</a>
                <button type="submit">Sign In</button>
            </form>
        </div>
        <div class="toggle-container">
            <div class="toggle">
                <div class="toggle-panel toggle-left">
                    <h1>Welcome Back!</h1>
                    <p>Enter your personal details to use all of site features</p>
                    <button class="hidden" id="login">Sign In</button>
                </div>
                <div class="toggle-panel toggle-right">
                    <h1>Hello, Friend!</h1>
                    <p>Register with your personal details to use all of site features</p>
                    <button class="hidden" id="register">Sign Up</button>
                </div>
            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='script.js') }}"></script>
</body>

</html>

Masha'erohom/website/templates/login.html
{% extends "base2.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="static/login&register.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='alert.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <title>تسجيل الدخول</title>
</head>     

<body>

    <div class="logo">
        <img src="static/logo.png">
        <!-- <a href="#">AsmrProg</a> -->
    </div>

    <div class="container" >
        <h1>تسجيل الدخول</h1>
        <!-- <div class="social-login">
            <button class="google">
                <i class='bx bxl-google'></i>
                Use Google
            </button>
            <button class="google">
                <i class='bx bxl-apple'></i>
                Use Apple
            </button>
        </div> -->
        <!-- <div class="divider">
            <div class="line"></div>
            <p>Or</p>
            <div class="line"></div>
        </div> -->

        <br>
        <br>

        <form method="post" action="{{ url_for('auth.login') }}">
            <label for="email">البريد الإلكتروني</label>
            <div class="custome-input">
                <input type="email" name="email" placeholder="بريدك الإلكتروني" autocomplete="off">
                <i class='bx bx-at'></i>
            </div>
            <label for="password">كلمة السر</label>
            <div class="custome-input">
                <input type="password" name="password" placeholder="كلمة السر">
                <i class='bx bx-lock-alt'></i>
            </div>
            <button class="login">سجل الدخول</button>
            <div class="links">
                <a href="#">اعادة ضبط كلمة السر</a>
                <a href="/sign-up">ليس لديك حساب؟</a>
            </div>
        </form>

    </div>
</body>

</html>
<!-- {% endblock %} -->

Masha'erohom/website/templates/register.html
{% extends "base2.html" %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="static/login&register.css">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='alert.css') }}">
    <title>Sign-Up Page</title>
</head>

<body>

    <div class="logo">
        <img src="static/logo.png">
        <!-- <a href="#">AsmrProg</a> -->
    </div>

    <div class="container">
        <h1>انشئ حساب جديد</h1>
        <!-- <div class="social-login">
            <button class="google">
                <i class='bx bxl-google'></i>
                Use Google
            </button>
            <button class="google">
                <i class='bx bxl-apple'></i>
                Use Apple
            </button>
        </div> -->
        <!-- <div class="divider">
            <div class="line"></div>
            <p>Or</p>
            <div class="line"></div>
        </div> -->

        <br>
        <br>

        <form method="post" action="{{ url_for('auth.sign_up') }}">
            <label for="email">البريد الالكتروني</label>
            <div class="custome-input">
                <input id="email" type="email" name="email" placeholder="بريدك الإلكتروني" autocomplete="off" value="{{ email }}">
                <i class='bx bx-at'></i>
            </div>
            <label for="email">الإسم</label>
            <div class="custome-input">
            <input id="firstName" type="text" name="firstName" placeholder="إسمك" autocomplete="off" value="{{ firstName }}">
                <i class='bx bx-user'></i>
            </div>
            <label for="password">كلمة السر</label>
            <div class="custome-input">
            <input id="password1" type="password" name="password1" placeholder="كلمة السر (8 حروف حد ادنى)">
                <i class='bx bx-lock-alt'></i>
            </div>
            <label for="password">تأكيد كلمة السر</label>
            <div class="custome-input">
                <input id="password2" type="password" name="password2" placeholder="تأكيد كلمة السر">
                <i class='bx bx-lock-alt'></i>
            </div>
            <button class="login" type="submit">تسجيل</button>
            <div class="links">
                <a href="/login">لديك حساب بالفعل؟</a>
            </div>
        </form>

    </div>
</body>

</html>
{% endblock %}